//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pranomi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public int ID { get; set; }
        public string AdressLine { get; set; }
        public string District { get; set; }
        public string Phone { get; set; }
        public int CustomersID { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual StateProvince StateProvince { get; set; }
    }
}
