//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pranomi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costs
    {
        public int ID { get; set; }
        public System.DateTime CostDate { get; set; }
        public string Description { get; set; }
        public decimal PriceExVat { get; set; }
        public decimal PriceInVat { get; set; }
        public bool IsPay { get; set; }
        public System.DateTime ExpryDate { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual CostCategory CostCategory { get; set; }
        public virtual Users Users { get; set; }
    }
}
