//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pranomi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Adress = new HashSet<Adress>();
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int ID { get; set; }
        public string Customer_Code { get; set; }
        public bool IsCompany { get; set; }
        public string TaxState { get; set; }
        public string TaxNumber { get; set; }
        public bool IsCustomer { get; set; }
        public decimal Balance { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Iban { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adress> Adress { get; set; }
        public virtual Competent Competent { get; set; }
        public virtual CustomerCategory CustomerCategory { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}
