//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pranomi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceLine = new HashSet<InvoiceLine>();
        }
    
        public int ID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string CurrencyName { get; set; }
        public decimal CurrencyValue { get; set; }
        public string InvoiceNumber { get; set; }
        public string Description { get; set; }
        public string FileUrl { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public decimal Total { get; set; }
        public decimal PayTotal { get; set; }
        public decimal Discount { get; set; }
        public bool IsPay { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int InvoiceKind { get; set; }
        public int PayKind { get; set; }
        public int CustomerID { get; set; }
        public int categoryID { get; set; }
        public int UserID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual InvoiceCategory InvoiceCategory { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLine { get; set; }
    }
}
