//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pranomi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.InvoiceLine = new HashSet<InvoiceLine>();
            this.OrderLine = new HashSet<OrderLine>();
            this.ProductTaxes = new HashSet<ProductTaxes>();
            this.ProductVaryant = new HashSet<ProductVaryant>();
        }
    
        public int ID { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsVirtual { get; set; }
        public decimal Stock { get; set; }
        public string PictureUrl { get; set; }
        public bool IsActive { get; set; }
        public int CategoryID { get; set; }
        public int UserID { get; set; }
        public int CurrencyID { get; set; }
        public decimal PurPriceExVat { get; set; }
        public decimal PurPriceInVat { get; set; }
        public decimal SalPriceExVat { get; set; }
        public decimal SalPriceInVat { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLine { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTaxes> ProductTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVaryant> ProductVaryant { get; set; }
    }
}
