//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pranomi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVaryant
    {
        public int ID { get; set; }
        public string Value { get; set; }
        public int ProductID { get; set; }
        public int VaryantID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Varyant Varyant { get; set; }
    }
}
