//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pranomi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafeAction
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int ActionKind { get; set; }
        public int KindID { get; set; }
        public decimal Amount { get; set; }
        public decimal LastBalance { get; set; }
        public int SafeID { get; set; }
        public int UserID { get; set; }
    
        public virtual Safe Safe { get; set; }
        public virtual Users Users { get; set; }
    }
}
